INSERT INTO TB_CATEGORY (NAME) VALUES ('Books');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Computers');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Games');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Music');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Smart');